logging:
    file: ./log/local
    level:
        com:
            song:
                '*': debug
    path: logs
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 5
        password: dudtn910
        url: jdbc:mysql://34.84.133.21:3306/johnber_bot?useSSL=false&serverTimezone=Asia/Seoul
        username: root
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    output:
        ansi:
            enabled: always
